# Generated by Django 4.2.7 on 2023-12-12 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("gid", models.IntegerField()),
                ("sid", models.IntegerField()),
                ("rev", models.IntegerField()),
                ("action", models.CharField(max_length=10)),
                ("msg", models.TextField()),
                ("json", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("src_addr", models.CharField(blank=True, max_length=30, null=True)),
                ("src_port", models.IntegerField(blank=True, null=True)),
                ("dst_addr", models.CharField(blank=True, max_length=30, null=True)),
                ("dst_port", models.IntegerField(blank=True, null=True)),
                ("proto", models.CharField(max_length=10)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "rule_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.rule"
                    ),
                ),
            ],
        ),
    ]
