# Generated by Django 4.2.7 on 2023-12-07 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rule",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="event",
            name="sid",
        ),
    ]
