# Generated by Django 4.2.7 on 2023-12-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user_ip', models.CharField(max_length=30)),
                ('http_method', models.CharField()),
                ('request_data', models.JSONField()),
            ],
        ),
    ]
