# Generated by Django 4.2.7 on 2023-12-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='endpoint',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
