# Generated by Django 4.2.7 on 2023-12-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_requestlog_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='response_status_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
